 ⍙Z⍙←⍙MUTE ⍙A⍙;⍙OUT
 ⍝Captures and returns the ⍙OUT output generated by statement ⍵
 ⍝ The result is a vector with ⍙TCNL at the front of each line.
 ⍙Z⍙←'⋄⍙OUT A⋄→(2≠⍴⍴A)/L1⋄A←1↓⍙TCNL ⍙MTOV A⋄L1:⍙Z⍙←⍙Z⍙,⍙TCNL,A'
 ⍙Z⍙←÷' '=1↑0⍴⎕FX ⍙VTOM ⍙Z⍙ ⍝ define the local ⍙OUT
 ⍙Z⍙←''                     ⍝ output buffer
 ⍎⍙A⍙
 ⍝ APLASCII.APLPLUS3 version 1.4 (1995.10.15)
