⌷systemvars←
<array><shape>8</shape>
<array><shape>3</shape><string>⎕io</string></array>
<array><shape>3</shape><string>⎕pp</string></array>
<array><shape>3</shape><string>⎕pw</string></array>
<array><shape>3</shape><string>⎕ct</string></array>
<array><shape>3</shape><string>⎕rl</string></array>
<array><shape>3</shape><string>⎕wa</string></array>
<array><shape>1</shape><string>⍞</string></array>
<array><shape>1</shape><string>⎕</string></array></array>
